name: 'Coverbot'
description: 'Add coverage info to a PR'
inputs:
  cover-file:  # id of input
    description: 'input cover file'
    required: false
    default: 'cover.out'
runs:
  using: "composite"
  steps:
    - name: Generating coverage
      if: ${{ github.action.pullrequest }} != null
      run: |
        echo {{ github.action.pullrequest }}
        go run ${{ github.action_path }} . --coverage-file ${{ inputs.cover-file }} --repo ${{ github.repository }} --issue ${{ github.action.pullrequest.issue }}
      shell: bash
