name: 'Coverbot'
description: 'Add coverage info to a PR'
inputs:
  cover-file:  # id of input
    description: 'input cover file'
    required: false
    default: 'cover.out'
runs:
  using: "composite"
  steps:
    - name: Generating coverage
      if: ${{ github.action.pullrequest }} != null
      run: |
        echo ${{ github.event }}
        echo ${{ github.event_name }}
        cat ${{ github.event_path }}
        cd ${{ github.action_path }} 
        go run . --coverage-file ${{ inputs.cover-file }} --repo ${{ github.repository }} --issue 1
      shell: bash
